name: Build Container

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - { GDAL_VERSION: "3.0.4", PROJ_VERSION: "6.2.1", PYTHON: "3.6" }
          - { GDAL_VERSION: "3.1.4", PROJ_VERSION: "6.2.1", PYTHON: "3.6" }
          - { GDAL_VERSION: "3.2.1", PROJ_VERSION: "7.2.1", PYTHON: "3.6" }
          - { GDAL_VERSION: "3.2.1", PROJ_VERSION: "7.2.1", PYTHON: "3.7" }
          - { GDAL_VERSION: "3.2.1", PROJ_VERSION: "7.2.1", PYTHON: "3.8" }
          - { GDAL_VERSION: "3.2.1", PROJ_VERSION: "7.2.1", PYTHON: "3.9" }

    name: Python ${{ matrix.PYTHON }} / GDAL ${{ matrix.GDAL_VERSION }} / PROJ ${{ matrix.PROJ_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/rbuffat/buildcontainer:gdal-${{ matrix.GDAL_VERSION }}-py-${{ matrix.PYTHON }}
          build-args: |
            GDAL_VERSION=${{ matrix.GDAL_VERSION }}
            PROJ_VERSION=${{ matrix.PROJ_VERSION }}
            BASE_IMAGE=python:${{ matrix.PYTHON }}-buster
